; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM7
upload_port = COM7
upload_speed = 115200
upload_flags =
    --before
    no_reset_no_sync
    --after
    hard_reset
build_src_filter = -<*> +<main.cpp>
lib_deps =
    sparkfun/SparkFun BNO080 Cortex Based IMU
    ayushsharma82/ElegantOTA

[env:esp32dev_manual]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM7
upload_port = COM7
upload_speed = 115200
upload_flags =
    --before
    no_reset_no_sync
    --after
    hard_reset
build_src_filter = -<*> +<main.cpp>
lib_deps =
    sparkfun/SparkFun BNO080 Cortex Based IMU
    ayushsharma82/ElegantOTA

[env:wifi_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<wifi_sensor_test.cpp>
lib_deps =
    sparkfun/SparkFun BNO080 Cortex Based IMU
